### PR TITLE
160 & 163 - add support for multiple local lidar dataset (#164)

### PR DESCRIPTION
**Pull request by rosepearson**
Added to upstream branch for further changes (tests, documentation, package version).

* Need a new `test_dem_generation_multiple` test with one local dataset and one from OpenTopography. Also include a `dataset_mapping` in the instruction. 
* Need to ensure there is a way of specifying the LiDAR layer precedence (as can't rely on order between the APIs and file_paths). Could set the order based on the mapping? or some other way - new instruction input.
* Ensure that if now `dataset_mapping` is specified in the instruction, then no `dataset_id` variable is created. 
* Update the documentation.

----
## 160 - Add dataset_id variable for raw dem
1. Passing the dataset id information by the `dataset_mapping` dict in the JSON instructions input (shown below) and then passing the `dataset_mapping` dict using metadata to where it is used. This way can be compatible with old test cases without dataset mapping information.
2. Using dataset name and dataset mapping dict to retrieve dataset id.
3. Saving dataset id as a variable in the dem objects. Dataset mapping dict as supplement information is also saved in the variable.
4. Tested single or multiple datasets with API scenarios but did not cover entire cases. Did not update documentation.

```
{
  "instructions": {
  ...
    "apis": {
      "lidar": {
        "open_topography": {
          "Rangiora_2014": {
            "crs": {
              "horizontal": 2193,
              "vertical": 7839
            }
          },
          "NZ20_Cant2": {
            "crs": {
              "horizontal": 2193,
              "vertical": 7839
            }
          }
    ...
    "dataset_mapping": {
      "Rangiora_2014": 2,
      "NZ20_Cant2": 31
    }
  ...
}
```

----
## 163 - Add support for multiple local lidar dataset
Current `lidar_dataset_info` (`get_lidar_datasets_info()` in `processor.py`) for local files does not support multiple datasets. If we define the instructions dictionary like the below example and pass it to `lidar_dataset_info` like: `lidar_datasets_info = self.instructions["local"]["lidar"]`, it will support multiple local datasets in the same way with API enabled process.

The contents of `instructions["local"]["lidar"]` are identical (ideally, may vary case by case) the same as the contents in `lidar_dataset_info`.
 while using API.

1. only need to define the corresponding dict in the instructions file, as the below example shows.
2. compatible with old test cases.

```
...
    "apis": {}
    "local": {
      "lidar": {
        "NZ20_Cant2": {
          "crs": {
            "horizontal": 2193,
            "vertical": 7839
          },
          "file_paths": [
            "../datastorage/LiDAR/NZ20_Cant2/CL2_BW24_2020_1000_0229.laz",
            ...
            "../datastorage/LiDAR/NZ20_Cant2/CL2_BW24_2020_1000_1230.laz"
           ],
          "tile_index_file": "../datastorage/LiDAR/NZ20_Cant2/NZ20_Cant2_TileIndex.zip"
        },
        "NZ18_AmuriCant": {
          "crs": {
            "horizontal": 2193,
            "vertical": 7839
          },
          "file_paths": [
            "../datastorage/LiDAR/NZ18_AmuriCant/CL2_BW24_2018_1000_0739.laz",
            ...
            "../datastorage/LiDAR/NZ18_AmuriCant/CL2_BW24_2018_1000_0838.laz"
          ],
          "tile_index_file": "../datastorage/LiDAR/NZ18_AmuriCant/NZ18_AmuriCant_TileIndex.zip"
        },
...
```

 - [x] Make code change
 - [x] Update tests
   - [x] Update / create new tests
   - [x] Ensure these tests have the expected behavour
   - [x] Test locally and ensure tests are passing
 - [x] Ensure tests passing on GH Actions
 - [x] Update documentation
   - [x] Doc strings
   - [x] Wiki
- [x] Update package (version.py & pyproject.toml) version (if needed)

### CODE REVIEW

**Comment by rosepearson** [comment]
Hi @xandercai, thanks for these two changes. I intend to adjust the expected input for local LiDAR datasets to include a folder containing all the LAZ/LAS files instead of the list of all files as I think this will make the instruction files a lot more manageable.

We could even assume the tile_index_file is in the same folder and remove that too.

Does that fit with your usage case? this would be:

```
    ...
      "lidar": {
        "NZ20_Cant2": {
          "crs": {
            "horizontal": 2193,
            "vertical": 7839
          },
          "folder_path": "../datastorage/LiDAR/NZ20_Cant2",
          "tile_index_file": "../datastorage/LiDAR/NZ20_Cant2/NZ20_Cant2_TileIndex.zip"
        },
        "NZ18_AmuriCant": {
          "crs": {
            "horizontal": 2193,
            "vertical": 7839
          },
          "folder_path": "../datastorage/LiDAR/NZ18_AmuriCant",
          "tile_index_file": "../datastorage/LiDAR/NZ18_AmuriCant/NZ18_AmuriCant_TileIndex.zip"
        },
        ...
```

**Comment by xandercai** [comment]
>  I intend to adjust the expected input for local LiDAR datasets to include a folder containing all the LAZ/LAS files instead of the list of all files ...

The input dict field `self.instructions["local"]["lidar"]` for local datasets is exactly the same as the input dict field from the API part, lines 561 - 579. If only give a folder name, I do not know if the following process would work without the `file_path` field.

And the application scenario is also different. The API approach only downloads files in ROI geometry, the remote servers will filter the file list for users, and users only need to take all download files to process. But the local approach means users already downloaded files, maybe much, much more files in the folder than this single process needed. If users do not assign a file path list filtered by ROI geometry but give a folder to process, then the time cost may be much higher if the ROI geometry is only a small part of the dataset.

**Comment by rosepearson** [comment]
Yup – I was going to make an upstream code change to address that. I’ll make the change and se what you think 😊

**Comment by rosepearson** [comment]
@xandercai thanks for your contribution. I've included the changes with a few adjustments to simplify the required instructions. Let me know what you think - although I may merge before your response as we can always fix things up in a later issue.

Basic additions are:
* Pull the local datasets into the renamed datasets key in the instructions (apis -> datasets).
* Perform all checks around the lidar_dataset mapping in the processor module and assume is valid by the time it gets to the dem module (e.g. no asserts in the dem module with just hard crash). Interested on your thoughts on this?

**Comment by xandercai** [comment]
Sorry for feeding back so late. We ported the code to the latest GeoFabrics and ran for over a month. It works very well. The new instruction structure is nice and clean. Thank you for your work!

**Pull request merged**
