### PR TITLE
57 other classifications

### PR DESCRIPTION
**Pull request by rosepearson**
DESCRIPTION OF PR:
 - [X] Make code change
 - [X] Update tests 
   - [X] Update / create new tests
   - [X] Ensure these tests have the expected behavour
   - [X] Test locally and ensure tests are passing
 - [x] Ensure tests passing on GH Actions
 - [x] Update documentation
   - [X] Doc strings
   - [x] Wiki 
  - [X] Update package version (if needed)

### CODE REVIEW

**Comment by rosepearson** [comment]
@AliceHarang I've updated the instruction file so that you can specify exactly which classifications of LiDAR points to keep - this will make is easy to for example make a DEM from ground and water points. Do you mind reviewing this please. A quick scan through the code changes should be sufficient.

**Comment by AliceHarang** [comment]
In the Wiki text, I think you have a spelling at the end: "Open Topography".

**Comment by rosepearson** [comment]
> In the Wiki text, I think you have a spelling at the end: "Open Topography".

Phew - there sure was! Thanks for picking that up @AliceHarang!

**Review by AliceHarang — APPROVED** [review]
Hi Rose,
It is a nice and usefull functionnality!
It will allow to test and use more effectively the Lidar classifications!
I am happy with it!

**Pull request merged**
