### PR TITLE
Processing DEM in chunks using Dask

### PR DESCRIPTION
**Pull request by rosepearson**
Generate DEM in chunks and used Dask to allow this to be done in parallel in a distributed system.

 - [x] Make code change - still need to set the number of workers based on the instruction file
 - [x] Update tests 
   - [x] Update / create new tests
   - [x] Ensure these tests have the expected behavour
   - [x] Test locally and ensure tests are passing
 - [x] Ensure tests passing on GH Actions
 - [x] Update documentation
   - [x] Doc strings
   - [x] Wiki 
  - [x] Update package version (if needed) 

From the review:
- [x] Using the builtin Python logging module
- [x] Avoid delayed as a decorator - cleaner interface as suggested
- [x] Move the dask client creation to a higher level so it is more visible
- [x] Look into removing the explicit compute call and instead saving the dense_dem to disk prior to an later steps - have created as an issue. See issue notes.

### CODE REVIEW

**Review by jennan — APPROVED** [review]
Hi @rosepearson,

Overall it looks very good :-). I have focused my attention on the `_add_tiled_lidar_chunked` function, as this is where most of the Dask related logic is:

- The logic is well split, so it's easy to understand how the Dask-array is built without knowing the details of the individual steps :+1:.

- I would advise to replace print statements & verbose parameter with logging using the Python standard library [logging module](https://docs.python.org/3/library/logging.html). This has multiple advantages:
  - one less parameter for the function
  - more fine-grained control on the messages (some can be just for debugging, some for warning, some for errors...) and when to report them
  - verbosity can be more centrally configure by the calling code

- (already addressed) Move dask cluster/client creation outside of the function, to leave the calling code the choice of the scheduler ("vanilla" dask scheduler or distributed scheduler), allow more flexible testing and reuse of the Dask cluster if needed. This could probably be parameterized in the `instructions.json` at some point to leave full control of which scheduler to use.

- (already addressed) avoid delayed as a decorator, create 2 functions (the core one and the decorated one) to allow testing in isolation of the core function (without having to deal with Dask), e.g.:

```
delayed_load_tiles_in_chunk = dask.delayed(load_tiles_in_chunk)
```

- The `compute()` call on `chunked_dem` may not be needed **if** the goal is only to later save it on disk. Avoiding `compute` would allow Dask to compute few chunks at a time and directly saving them on disk, removing the need for a large amount of memory (if the entire dataset is huge).

Also, running `src/main.py` on example data you provided me (`lower_waikanae_test2.zip`) works well on my machine (Windows laptop, i7-10810U, 32GB of RAM), took:

- 307s (chunk 100, 2 workers, 1 process per worker)
- 225s (chunk 100, 4 workers, 1 process per worker)

and the workers seemed properly busy :) (100% CPU usage, no concerning I/Os reported in Dask dashboard, no idle workers).

**Comment by rosepearson** [comment]
Awesome thanks for the review @jennan. The suggestions all look good. I will work through making those changes (aside from those I've just addressed) in the next few days. 

More a note to myself: I am also tracking down one last bug relating to self intersection errors when Bathymetry is included for the lower_waikanae_test case on my machine. It appears to happen after the Dask stage but I get Dask errors - perhaps due to threads that haven't quite been tidied yet. I should look in debug mode and possibly without using Dask if I keep getting the errors mentioning Dask.

**Comment by rosepearson** [comment]
FYI Luke - changes associated with Dask & some really helpful comments from @jennan 

I'll hopefully land it before you make any insightful comments - but please make them anyway and I can spin them out in new issues :)

**Review by LukeParky — COMMENTED** [review]
@rosepearson, I had a look at this for my own curiosity on using dask. It looks like it integrates well for such a powerful library.

I like what you've done with the logging, and the changes to `processor.py`.
I skipped through `dem.py` and at first glance struggled to understand exactly where the dask processing was being used but that was cleared up when I read the last two lines of the file.

Overall it was well written and structured, well done. Thanks for showing me around dask, it would be great to see a quick demo next time we see each other, if you aren't too busy.

**Pull request merged**
