### PR TITLE
52 benchmarking

### PR DESCRIPTION
**Pull request by rosepearson**
Added script for benchmarking performance of geofabrics for a dataset at a range of chunk-sizes and number-of-CPU-cores:
 - [x] Make code change
 - [x] ~~Update tests~~
   - [x] ~~Update / create new tests~~
   - [x] ~~Ensure these tests have the expected behavour~~
   - [x] ~~Test locally and ensure tests are passing~~
 - [x] Ensure tests passing on GH Actions
 - [x] Update documentation
   - [x] Doc strings
   - [x] Wiki 
  - [x] ~~Update package version (if needed)~~

### CODE REVIEW

**Comment by rosepearson** [comment]
Hi @Pooja3894 - I've updated the documentation associated with this script and tested it on my computer. Could you give it a review at some point please.

**Review by Pooja3894 — APPROVED** [review]
helpful in selecting chunk sizes and cores efficiently. Great work  @rosepearson

**Comment by rosepearson** [comment]
Awesome! Thanks @Pooja3894. I will merge in now. Out of interest - do you think there should be tests added for the benchmarking file? I'm just wondering if this is something I should add in future.

**Comment by Pooja3894** [comment]
I think adding the instruction file to run the script should be enough. That worked for me.

**Pull request merged**
