### PR TITLE
extract file section out of delayed_load_tiles_in_chunk

### PR DESCRIPTION
**Pull request by rosepearson**
PR for ease of diff comparison

This seems to avoid garbage collection related issues for the large test case, but add a significant runtime.

DESCRIPTION OF PR:
 - [x] Make code change
 - [x] ~~Update tests~~ __No changes__ 
 - [x] Ensure tests passing on GH Actions
 - [x] Update documentation
   - [x] Doc strings
   - [x] Wiki 
  - [x] Update package version (if needed)

### CODE REVIEW

**Comment by rosepearson** [comment]
Just a note on some things for @rosepearson to look at on this branch:
1. runtime for small/med example with & without the changes on this branch
2. appropriate chunk size for the large example (say 100,000 tasks)
3. consider improvements to setup efficiency (geometric manipulations)

**Comment by rosepearson** [comment]
@jennan nice changes. I am satisfied that these definitely improve things! Let me know what you think!

**Comment by rosepearson** [comment]
Separate case to explore a few other options for reducing the setup time https://github.com/rosepearson/GeoFabrics/issues/130

**Review by jennan — APPROVED** [review]
Awesome @rosepearson 👍

**Pull request merged**
